# Generated by Django 5.1.5 on 2025-01-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_seat_timeslot_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_available',
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.seat')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.timeslot')),
            ],
            options={
                'unique_together': {('seat', 'time_slot')},
            },
        ),
    ]
